### ISSUE TITLE
Not working fine with Android

### ISSUE THREAD

**Issue by SasiKumar-Ramesh** [underscopeio/react-native-floating-hearts#10]
I followed the quick start guide and tried to deploy the app in android. 
But it is not working. It throws me the error 
undefined is not an object(evalutation '_react.propTypes.string' . 
Also I tried this  import PropTypes from 'prop-types';
![screenshot_2018-12-13-16-33-54-618_com floatingheart](https://user-images.githubusercontent.com/20661760/49934952-bf9d4d80-fef5-11e8-9d9b-58db3384bfd3.png)

**Comment by ignacioola** [comment]
Hey! I've upgraded the npm version, so please install the latest one.

**Comment by SasiKumar-Ramesh** [comment]
I am using NPM version 5.6.0 .

**Comment by ignacioola** [comment]
Oh sorry, I meant I released a new version (`0.0.8`) try that one.

**Comment by SasiKumar-Ramesh** [comment]
Sorry ignacioola. I tried the lates version 0.0.8 But the error remains the same. 
But instead of quick start, I downloaded FloatingHeart.js and HeartShape.js. And then I commented those  `style: View.propTypes.style`  styles. And it works fine for me.

**Comment by ignacioola** [comment]
It should be fixed in version `0.0.9`

**Comment by SasiKumar-Ramesh** [comment]
No ignacioola. It's not fixed. I am using the version 0.0.9. Still throwing same error in android. Please look those screenshots.

![screenshot 2018-12-26 at 12 49 13 pm](https://user-images.githubusercontent.com/20661760/50436713-3c282700-090d-11e9-822b-afd937818422.png)
![screenshot 2018-12-26 at 12 50 43 pm](https://user-images.githubusercontent.com/20661760/50436715-3f231780-090d-11e9-9dec-119ce9727379.png)
![screenshot_2018-12-13-16-33-54-618_com floatingheart](https://user-images.githubusercontent.com/20661760/50436732-4d713380-090d-11e9-9806-a51d39b4563c.png)
